#! /bin/sh
set -eu

if [ -d /tmp/certs ] && [ "$(ls -A /tmp/certs/* 2> /dev/null)" ]; then
    echo "Updating certificates"
    cp /tmp/certs/* /usr/local/share/ca-certificates
    update-ca-certificates
fi

echo "Starting agent..."
exec /bin/vault-raft-snapshot-agent