on:
  workflow_dispatch:
  workflow_call:
  push:
    paths-ignore:
      - './README.md'

name: Build
jobs:
  compile-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: compile linux amd64
        env:
          GOARCH: amd64
          GOOS: linux
        run: |
          go get -v ./...
          go build -o vault_raft_snapshot_agent_linux_amd64 \
          -a \
          -trimpath \
          -ldflags "-s -w -extldflags '-static'" \
          -tags 'osusergo netgo static_build'
      - name: Upload amd64 binary
        uses: actions/upload-artifact@v1
        with:
          name: binaries
          path: vault_raft_snapshot_agent_linux_amd64
  compile-linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: compile arm64
        env:
          GOARCH: arm64
          GOOS: linux
        run: |
          go get -v ./...
          go build -o vault_raft_snapshot_agent_linux_arm64 \
          -a \
          -trimpath \
          -ldflags "-s -w -extldflags '-static'" \
          -tags 'osusergo netgo static_build'
      - name: Upload arm64 binary
        uses: actions/upload-artifact@v1
        with:
          name: binaries
          path: vault_raft_snapshot_agent_linux_arm64
  compile-linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: compile arm
        env:
          GOARCH: arm
          GOOS: linux
        run: |
          go get -v ./...
          go build -o vault_raft_snapshot_agent_linux_arm \
          -a \
          -trimpath \
          -ldflags "-s -w -extldflags '-static'" \
          -tags 'osusergo netgo static_build'
      - name: Upload arm binary
        uses: actions/upload-artifact@v1
        with:
          name: binaries
          path: vault_raft_snapshot_agent_linux_arm
