name: Compile Binaries

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      upload-artifacts:
        required: false
        type: boolean
        default: true
  push:
    branches:
    - '**'
    tags-ignore:
    - "**"
    paths-ignore:
    - "deploy/**"
    - "**Dockerfile"
    - "**README.md"
    - "build/VERSION"
    - ".github/workflows/*-helm-charts.yml"
    - ".github/workflows/release*.yml"
  pull_request:
    paths-ignore:
    - "deploy/**"
    - "**README.md"
    - "**Dockerfile"
    - "build/VERSION"
    - ".github/workflows/*-helm-charts.yml"
    - ".github/workflows/release*.yml"

env:
  ARTIFACT_RETENTION_DAYS: 1

jobs:
  compile-binaries:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        platform:
        - linux/amd64
        - linux/arm64
        - linux/arm

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3

    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Compile binary
      run: |
        mkdir ./dist
        chmod +x ./build/build.sh
        ./build/build.sh . ./dist ${{ github.ref_name }} ${{ matrix.platform }}

    - name: Upload binary
      if: inputs.upload-artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: ./dist/*
        retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
