name: Compile Binaries

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths-ignore:
    - "deploy/**"
  pull_request:
    paths-ignore:
    - "!deploy/**"

env:
  ARTIFACT_RETENTION_DAYS: 1

jobs:
  compile-binaries:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        platform:
        - linux/amd64
        - linux/arm64
        - linux/arm

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@master

    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Compile binary
      run: |
        mkdir ./dist
        chmod +x ./build/build.sh
        ./build/build.sh . ./dist ${{ matrix.platform }}

    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: ./dist/*
        retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
