name: Compile Binaries

on:
  workflow_dispatch:
    inputs:
      upload-artifacts:
        description: "should the binaries be stored?"
        type: boolean
        default: false
      artifact-retention-days:
        description: "how many days should binaries be retained?"
        type: number
        default: 1
  workflow_call:
    inputs:
      upload-artifacts:
        type: boolean
        default: true
      artifact-retention-days:
        description: "how many days should binaries be retained?"
        type: number
        default: 1
  push:
    branches:
    - '**'
    tags-ignore:
    - "**"
    paths-ignore:
    - "README.md"
    - "**Dockerfile"
    - ".github/workflows/lint.yml"
    - ".github/workflows/release*.yml"
  pull_request:
    paths-ignore:
    - "Dockerfile"
    - "**README.md"
    - ".github/workflows/lint.yml"
    - ".github/workflows/release*.yml"

concurrency:
  group: compile-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile-binaries:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        platform:
        - linux/amd64
        - linux/arm64
        - linux/arm

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3

    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Compile binary
      run: |
        mkdir ./dist
        chmod +x ./build/build.sh
        ./build/build.sh -b . -d ./dist -p ${{ matrix.platform }} -v ${{ github.ref_name }}

    - name: Upload binary
      if: inputs.upload-artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: ./dist/*
        retention-days: ${{ inputs.artifact-retention-days }}
