name: Release

on:
  workflow_dispatch:
  release:
    types:
    - published

jobs:
  compile-binaries:
    uses: ./.github/workflows/compile-binaries.yml

  upload-release-assets:
    runs-on: ubuntu-latest
    needs:
    - compile-binaries

    steps:
    - name: Download binaries from earlier jobs
      uses: actions/download-artifact@v3
      with:
        name: binaries

    - name: Upload Binaries
      id: upload-release-asset-linux_amd64
      uses: AButler/upload-release-assets@v2.0.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        files: binaries/*
        release-tag: ${{ github.ref_name }}

  publish-container-image:
    needs:
    - compile-binaries
    uses: ./.github/workflows/publish-container-image.yml
