name: Release Helm-Charts

on:
  workflow_dispatch:
  release:
    types:
    - published

env:
  CHARTS_DIR: ./deploy/helm-charts

jobs:
  release-charts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v3
        
    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.5.0
      with:
        charts_dir: ${{ env.CHARTS_DIR }}
        mark_as_latest: false
      env:
        CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        CR_RELEASE_TEMPLATE: ${{ github.ref_name }}
