name: Release

on:
  workflow_dispatch:
  push:
    branches:
    - master
    tags-ignore:
    - "**"
    paths:
    - "build/VERSION"

concurrency:
  group: release-binaries-${{ github.ref }}
  cancel-in-progress: true


jobs:
  compile-binaries:
    uses: ./.github/workflows/compile-binaries.yml

  create-release:
    runs-on: ubuntu-latest
    needs:
    - compile-binaries

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3

    - name: Download binaries from earlier jobs
      uses: actions/download-artifact@v3
      with:
        name: binaries
        path: dist/

    - name: Read Binaries Version
      id: release_version
      run: echo "value=$(cat build/VERSION)" >> "$GITHUB_OUTPUT"

    - name: Create Release
      uses: "softprops/action-gh-release@v1"
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: v${{ steps.release_version.outputs.value }}
        name: "Release v${{ steps.release_version.outputs.value }}"
        prerelease: true
        generate_release_notes: true
        files: |
          LICENSE.txt
          dist/*
