name: Release

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/compile-binaries.yml

  upload-release-assets:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Download binaries from earlier jobs
      uses: actions/download-artifact@v1
      with:
        name: binaries

    - name: Upload Binaries
      id: upload-release-asset-linux_amd64
      uses: AButler/upload-release-assets@v2.0.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        files: binaries/*
        release-tag: ${{ github.ref_name }}

  publish-container-image:
    uses: ./.github/workflows/publish-container-image.yml
