name: Release Binaries

on:
  workflow_dispatch:
  workflow_call:


permissions:
  contents: read
  pull-requests: read
  packages: write

concurrency:
  group: release-binaries-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile-binaries:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/compile.yml
    secrets: inherit

  release-binaries:
    runs-on: ubuntu-latest
    needs:
    - compile-binaries

    steps:
    - name: Download binaries from earlier jobs
      uses: actions/download-artifact@v4
      with:
        pattern: binary-*
        path: dist/
        merge-multiple: true

    - name: Upload binaries to release

      uses: "ncipollo/release-action@v1"
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag: ${{ github.ref.name }}
        allowUpdates: true
        artifactErrorsFailBuild: true
        omitBodyDuringUpdate: true
        omitDraftDuringUpdate: true
        omitNameDuringUpdate: true
        replacesArtifacts: true
        artifacts: dist/*
