name: Release Helm-Charts
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      latest-release:
        type: string
        required: true

jobs:
  get-latest-release:
    if: inputs.latest_release == ''
    runs-on: ubuntu-latest

    outputs:
      latest-release: ${{ steps.latest-release.outputs.tag_name }}

    steps:
    - uses: cardinalby/git-get-release-action@v1
      id: latest-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        latest: true
        draft: false
        prerelease: false
        doNotFailIfNotFound: true

  trigger-helm-release:
    if: always() && !cancelled() && !failure() && (inputs.latest-release || needs.get-latest-release.outputs.latest-release) == github.ref_name
    runs-on: ubuntu-latest
    needs:
      - get-latest-release

    steps:
    - name: Trigger Release of Helm-Charts
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.HELM_GITHUB_TOKEN }}
        repository: Argelbargel/vault-raft-snapshot-agent-helm
        event-type: update-vault-raft-snapshot-agent-images
        client-payload: '{ "appVersion": "${{ github.ref_name }}" }'
