on: push
name: Build
jobs:
  release-linux-amd64:
    container:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: compile and release
        env:
          GOARCH: amd64
          GOOS: linux
        run: |
          go get -v ./...
          go build
